// ============================================================
// Problem Validator
// ------------------------------------------------------------
// Deterministic validation of algorithm problems generated by
// the LLM. This does NOT rely on the model to judge correctness —
// it checks structure, format, and runs the reference solution
// against test cases using Pyodide (browser-side WASM Python).
// ============================================================

import { AlgorithmProblem } from '@/types';
import { KNOWLEDGE_TOPICS } from '@/lib/knowledge/topics';

export type ValidationSeverity = 'error' | 'warning' | 'info';

export interface ValidationIssue {
  field: string;
  severity: ValidationSeverity;
  message: string;
}

export interface ValidationResult {
  valid: boolean;
  score: number; // 0-100
  issues: ValidationIssue[];
  /** Test case execution results (if reference solution was run) */
  testExecution?: {
    total: number;
    passed: number;
    failed: number;
    details: Array<{ input: string; expected: string; actual: string; passed: boolean }>;
  };
}

// ============================================================
// Static validation (no Pyodide needed)
// ============================================================

export function validateProblemStructure(problem: AlgorithmProblem): ValidationIssue[] {
  const issues: ValidationIssue[] = [];

  // Required string fields
  const requiredStrings: Array<[string, string]> = [
    ['id', problem.id],
    ['title', problem.title],
    ['topicId', problem.topicId],
    ['description', problem.description],
    ['starterCode', problem.starterCode],
    ['solution', problem.solution],
    ['timeComplexity', problem.timeComplexity],
    ['spaceComplexity', problem.spaceComplexity],
  ];

  for (const [field, value] of requiredStrings) {
    if (!value || !value.trim()) {
      issues.push({ field, severity: 'error', message: `${field} 不能为空` });
    }
  }

  // ID format: lowercase, hyphens, alphanumeric
  if (problem.id && !/^[a-z0-9][a-z0-9-]*$/.test(problem.id)) {
    issues.push({
      field: 'id',
      severity: 'warning',
      message: 'id 应为小写字母、数字和短横线，如 two-sum',
    });
  }

  // Difficulty range
  if (problem.difficulty < 1 || problem.difficulty > 5) {
    issues.push({
      field: 'difficulty',
      severity: 'error',
      message: `难度 ${problem.difficulty} 不在有效范围 1-5`,
    });
  }

  // Topic ID should exist in knowledge base (or be a known pattern)
  if (problem.topicId && !KNOWLEDGE_TOPICS.find((t) => t.id === problem.topicId)) {
    issues.push({
      field: 'topicId',
      severity: 'warning',
      message: `topicId "${problem.topicId}" 不在知识库中，将使用默认知识点`,
    });
  }

  // Examples: at least 1, each with input and output
  if (!problem.examples || problem.examples.length === 0) {
    issues.push({
      field: 'examples',
      severity: 'error',
      message: '至少需要 1 个示例',
    });
  } else {
    problem.examples.forEach((ex, i) => {
      if (!ex.input && !ex.output) {
        issues.push({
          field: `examples[${i}]`,
          severity: 'warning',
          message: `示例 ${i + 1} 的输入和输出都为空`,
        });
      }
    });
  }

  // Constraints: at least 1
  if (!problem.constraints || problem.constraints.length === 0) {
    issues.push({
      field: 'constraints',
      severity: 'warning',
      message: '建议至少提供 1 条约束条件',
    });
  }

  // Hints: at least 3, progressive
  if (!problem.hints || problem.hints.length < 3) {
    issues.push({
      field: 'hints',
      severity: 'warning',
      message: '建议至少提供 3 条分级提示',
    });
  }

  // Starter code: must contain a function definition
  if (problem.starterCode && !/def\s+\w+\s*\(/.test(problem.starterCode)) {
    issues.push({
      field: 'starterCode',
      severity: 'error',
      message: 'starterCode 必须包含函数定义 (def ...)',
    });
  }

  // Test cases: at least 3, each with input and expectedOutput
  if (!problem.testCases || problem.testCases.length < 3) {
    issues.push({
      field: 'testCases',
      severity: 'error',
      message: `至少需要 3 个测试用例，当前 ${problem.testCases?.length || 0} 个`,
    });
  } else {
    problem.testCases.forEach((tc, i) => {
      if (!tc.input && !tc.expectedOutput) {
        issues.push({
          field: `testCases[${i}]`,
          severity: 'error',
          message: `测试用例 ${i + 1} 的输入和期望输出都为空`,
        });
      }
    });
  }

  // Solution: must contain a function definition
  if (problem.solution && !/def\s+\w+\s*\(/.test(problem.solution)) {
    issues.push({
      field: 'solution',
      severity: 'warning',
      message: '参考解答应包含函数定义',
    });
  }

  // Complexity notation
  if (problem.timeComplexity && !/^O\(/.test(problem.timeComplexity)) {
    issues.push({
      field: 'timeComplexity',
      severity: 'info',
      message: `时间复杂度建议使用大O表示法，如 O(n)`,
    });
  }

  return issues;
}

// ============================================================
// Dynamic validation (requires Pyodide)
// Runs the reference solution against all test cases to verify
// that expected outputs are actually correct.
// ============================================================

/**
 * Extract the function name from Python code.
 */
function extractFunctionName(code: string): string {
  const match = code.match(/^def\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*\(/m);
  return match ? match[1] : 'solution';
}

/**
 * Parse a test input string into Python arguments.
 * Handles formats like:
 *   "[2,7,11,15], 9"
 *   "nums = [2,7,11,15], target = 9"
 *   '"hello"'
 *   "3"
 */
function parseTestInput(input: string): string {
  if (!input) return '';
  // Remove "var = " prefixes: "nums = [2,7], target = 9" → "[2,7], 9"
  return input
    .replace(/[a-zA-Z_][a-zA-Z0-9_]*\s*=\s*/g, '')
    .trim();
}

/**
 * Run the reference solution against all test cases using Pyodide.
 * Returns detailed pass/fail results.
 *
 * This function dynamically imports PyodideRunner to avoid
 * loading Pyodide unless validation is actually needed.
 */
export async function validateTestCases(
  problem: AlgorithmProblem
): Promise<NonNullable<ValidationResult['testExecution']>> {
  const { loadPyodide, runTestCases } = await import('@/components/PyodideRunner');

  await loadPyodide();

  const functionName = extractFunctionName(problem.solution || problem.starterCode);
  const result = await runTestCases(
    problem.solution || problem.starterCode,
    problem.testCases,
    functionName
  );

  const details = (result.testResults?.failures || []).map((f) => ({
    input: f.input,
    expected: f.expected,
    actual: f.actual,
    passed: false,
  }));

  // Build full details array (passed + failed)
  const allDetails: Array<{ input: string; expected: string; actual: string; passed: boolean }> = [];
  const passedCount = result.testResults?.passed || 0;
  const totalCount = result.testResults?.total || problem.testCases.length;

  // If we have failures, mark them; otherwise all passed
  if (details.length > 0) {
    // We need to also include the passed ones
    const failedInputs = new Set(details.map((d) => d.input));
    for (const tc of problem.testCases) {
      const parsed = parseTestInput(tc.input);
      const failed = details.find((d) => d.input === parsed || d.input === tc.input);
      if (failed) {
        allDetails.push(failed);
      } else {
        allDetails.push({
          input: tc.input,
          expected: tc.expectedOutput,
          actual: '(通过)',
          passed: true,
        });
      }
    }
  } else {
    // All passed (or no test results)
    for (const tc of problem.testCases) {
      allDetails.push({
        input: tc.input,
        expected: tc.expectedOutput,
        actual: tc.expectedOutput,
        passed: true,
      });
    }
  }

  return {
    total: totalCount,
    passed: passedCount,
    failed: totalCount - passedCount,
    details: allDetails,
  };
}

// ============================================================
// Full validation pipeline
// ============================================================

export async function validateProblem(
  problem: AlgorithmProblem,
  options?: { runTests?: boolean }
): Promise<ValidationResult> {
  const runTests = options?.runTests ?? true;
  const issues = validateProblemStructure(problem);

  let testExecution: ValidationResult['testExecution'];

  if (runTests && problem.solution && problem.testCases.length > 0) {
    try {
      testExecution = await validateTestCases(problem);

      if (testExecution.failed > 0) {
        issues.push({
          field: 'testCases',
          severity: 'error',
          message: `参考解答未通过 ${testExecution.failed}/${testExecution.total} 个测试用例，测试用例或解答可能有误`,
        });
      }
    } catch (err) {
      issues.push({
        field: 'solution',
        severity: 'warning',
        message: `无法运行参考解答验证：${err instanceof Error ? err.message : String(err)}`,
      });
    }
  }

  // Calculate score
  const errors = issues.filter((i) => i.severity === 'error').length;
  const warnings = issues.filter((i) => i.severity === 'warning').length;
  const testPassRate = testExecution
    ? testExecution.passed / testExecution.total
    : 1;

  const score = Math.max(
    0,
    Math.round(
      100 - errors * 25 - warnings * 10 - (1 - testPassRate) * 30
    )
  );

  return {
    valid: errors === 0 && testPassRate === 1,
    score,
    issues,
    testExecution,
  };
}

/**
 * Quick synchronous check (structure only, no Pyodide).
 * Useful for fast filtering before the full async validation.
 */
export function quickValidate(problem: AlgorithmProblem): boolean {
  const issues = validateProblemStructure(problem);
  return issues.filter((i) => i.severity === 'error').length === 0;
}
